# Generated by Django 2.1.15 on 2020-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Employee', 'Employee'), ('Manager', 'Manager'), ('HR', 'HR')], max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Middle_Name',
            field=models.CharField(default='', help_text='employee middle name', max_length=20, null=True),
        ),
    ]
