# Generated by Django 2.1.15 on 2020-02-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200221_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='ssnitnumber',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tinnumber',
        ),
        migrations.AlterField(
            model_name='leave',
            name='defaultdays',
            field=models.PositiveIntegerField(blank=True, default=21, null=True, verbose_name='Leave days per year counter'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='enddate',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
    ]
