# Generated by Django 2.1.15 on 2020-02-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200225_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(default='Unspecified Reason', help_text='add additional information for leave', max_length=255, null=True, verbose_name='Reason for Leave'),
        ),
    ]
