# Generated by Django 2.2.10 on 2020-02-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200226_1837'),
        ('accounts', '0007_auto_20200226_1706'),
    ]

    operations = [
    ]
