# Generated by Django 2.1.15 on 2020-02-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200226_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_to',
            field=models.ForeignKey(blank=True, help_text='Reporting To', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='accounts.Employee'),
        ),
    ]
