# Generated by Django 2.1.15 on 2020-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employee_reporting_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30, verbose_name='Group Name')),
                ('group_mail', models.EmailField(default=None, max_length=255, verbose_name='Email')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
        ),
    ]
