# Generated by Django 2.2.10 on 2020-02-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20200227_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(default='Unspecified Reason', help_text='add additional information for leave', max_length=255, null=True, verbose_name='Reason for Leave'),
        ),
    ]
