# Generated by Django 2.2.10 on 2020-02-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_mailinggroup'),
        ('accounts', '0009_auto_20200227_1457'),
    ]

    operations = [
    ]
