# Generated by Django 2.1.15 on 2020-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20200227_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('Senior High', 'Senior High School'), ('Junior High', 'Junior High School'), ('Primary Level', 'Primary School'), ('Tertiary', 'Tertiary/University/Polytechnic'), ('O-LEVEL', 'OLevel'), ('Other', 'Other')], default='Senior High', help_text='highest educational standard ie. your last level of schooling', max_length=40, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('Not Known', 'Not Known')], default='male', max_length=8, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Dr', 'Dr'), ('Sir', 'Sir'), ('Madam', 'Madam')], default='Mr', max_length=4, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(default='Unspecified Reason', help_text='add additional information for leave', max_length=255, verbose_name='Reason for Leave'),
        ),
    ]
