# Generated by Django 2.1.15 on 2020-03-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200302_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='religion',
        ),
    ]
