# Generated by Django 2.1.15 on 2020-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200303_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('planned', 'Planned Leave'), ('workfromhome', 'Work From Home'), ('compoff', 'Compensatory Off')], default='sick', max_length=25, null=True),
        ),
    ]
