# Generated by Django 2.1.15 on 2020-03-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200303_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='planned_5_days',
            field=models.BooleanField(default=True, verbose_name='Once applied for 5 days or not?'),
        ),
    ]
