# Generated by Django 2.1.15 on 2020-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_employee_planned_5_days'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='leave',
        #     name='defaultdays',
        # ),
        # migrations.AddField(
        #     model_name='leave',
        #     name='defaultdays_casual',
        #     field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Casual Leave days per year counter'),
        # ),
        # migrations.AddField(
        #     model_name='leave',
        #     name='defaultdays_planned',
        #     field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Planned Leave days per year counter'),
        # ),
        # migrations.AddField(
        #     model_name='leave',
        #     name='defaultdays_sick',
        #     field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Sick Leave days per year counter'),
        # ),
    ]
