# Generated by Django 2.1.15 on 2020-03-06 06:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200305_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dateissued',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeeid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='othername',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='residence',
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, max_length=125, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('Senior High', 'Senior High School'), ('Junior High', 'Junior High School'), ('Primary Level', 'Primary School'), ('Tertiary', 'Tertiary/University/Polytechnic'), ('O-LEVEL', 'OLevel'), ('Other', 'Other')], default='Senior High', max_length=40, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profiles', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastwork',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Last Place of Work'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position Held'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+233240000000', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='leave',
            name='defaultdays_casual',
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Casual Leave days per year counter'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='defaultdays_planned',
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Planned Leave days per year counter'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='defaultdays_sick',
            field=models.PositiveIntegerField(blank=True, default=7, null=True, verbose_name='Sick Leave days per year counter'),
        ),
    ]
