# Generated by Django 2.1.15 on 2020-03-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200306_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('planned', 'Planned Leave'), ('workfromhome', 'Work From Home'), ('compoff', 'Compensatory Off')], default='sick', max_length=25, null=True),
        ),
    ]
